apiVersion: v1
kind: Service
metadata:
  name: gentlefisy-webapp

spec:
  selector:
    app: webapp
  
  ports:
    - name: http
      port: 80
      nodePort: 30080
   
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: gentlefisy-queue

spec:
  selector:
    app: queue
  
  ports:
    - name: http
      port: 8161
      nodePort: 30010
   
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: position-tracker

spec:
  selector:
    app: position-tracker
  
  ports:
    - name: http
      port: 8080

  type: ClusterIP  

  ---
apiVersion: v1
kind: Service
metadata:
  name: api-gatway

spec:
  selector:
    app: api-gatway
  
  ports:
    - name: http
      port: 8080
      nodePort: 30020

  type: ClusterIP  