apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accesModes:
    - ReadWriteOnce
  resources: 
    request:
      storage: 20Gi

---
apuVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  capacity:
    storage: 20Gi
  accesModes:
    - ReadWriteOnce
  hostpath:
    path: "/mnt/some new/directories/structure"  
    type: DirectoryOrCreate