apiVersion: v1
kind: Service
metadata:
  name: gentlefisty-webapp

spec:
  selector:
    app: webapp
    release: "0"
  
  ports:
    - name: http
      port: 80
      nodePort: 30080
   
  type: NodePort
